Repository Syaoran26/repapic-shop, pull requests merged in 2024-04, with the labels that each got.

#3 Login/Register Form logic
  client/package-lock.json
  client/package.json
  client/public/images/characters/character_1.png
  client/public/images/characters/character_4.png
  client/public/images/characters/character_5.png
  client/public/images/characters/character_6.png
  client/public/images/characters/character_8.png
  client/src/App.tsx
  client/src/components/Icons.tsx
  client/src/config/router.tsx
  client/src/features/auth/authSlice.ts
  client/src/layouts/BaseLayout.tsx
  client/src/pages/ErrorBoundary/ErrorBoundary.tsx
  client/src/pages/ErrorBoundary/index.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/LoginForm.tsx
  client/src/pages/Register/Register.tsx
  client/src/pages/Register/RegisterForm.tsx
  client/src/routes/publicRoutes.ts
  client/src/routes/router/authRouter.tsx
  client/src/routes/router/baseRouter.tsx
  client/src/routes/router/index.tsx
  client/src/routes/router/mainRouter.tsx
  client/src/theme/components/alert.modifier.tsx
  client/src/types/ErrorResponseType.tsx
  client/src/utils/constants.ts
  server/package-lock.json
  server/package.json
  server/src/index.js
Labels: Resolved

#7 Shop Page
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/public/images/backgrounds/placeholder.svg
  client/src/App.scss
  client/src/App.tsx
  client/src/app/store.ts
  client/src/components/ProductCard.tsx
  client/src/config/routes.ts
  client/src/features/products/optionsSlice.ts
  client/src/features/products/productsSlice.ts
  client/src/hooks/index.ts
  client/src/hooks/useDebounce.ts
  client/src/hooks/useMount.ts
  client/src/hooks/useUpdateEffect.ts
  client/src/index.tsx
  client/src/layouts/MainLayout.tsx
  client/src/layouts/components/Footer.tsx
  client/src/layouts/components/Header.tsx
  client/src/pages/ErrorBoundary/ErrorBoundary.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Shop/Filter.tsx
  client/src/pages/Shop/ProductGrid.tsx
  client/src/pages/Shop/Shop.tsx
  client/src/pages/Shop/constants.ts
  client/src/pages/Shop/index.ts
  client/src/routes/router/mainRouter.tsx
  client/src/theme/components/index.ts
  client/src/theme/components/menuItem.modifier.tsx
  client/src/theme/components/pagination.modifier.tsx
  client/src/theme/components/paper.modifier.tsx
  client/src/theme/components/skeleton.modifier.tsx
  client/src/utils/format.ts
Labels: Need to be reviewed

#10 change password and forgot password
  server/package-lock.json
  server/package.json
  server/src/app/controllers/auth.js
  server/src/app/controllers/me.js
  server/src/routes/auth.js
  server/src/routes/me.js
  server/src/utils/email.js
Labels: Need to be reviewed

#9 Page About us
  .vscode/settings.json
  client/public/images/about/testimonials.jpg
  client/public/images/about/vision.jpg
  client/public/images/about/what_1.png
  client/public/images/about/what_2.png
  client/public/images/avatar/avatar_2.jpg
  client/public/images/avatar/avatar_3.jpg
  client/public/images/avatar/avatar_4.jpg
  client/public/images/avatar/avatar_5.jpg
  client/public/images/avatar/avatar_6.jpg
  client/public/images/avatar/avatar_7.jpg
  client/public/images/backgrounds/hero.jpg
  client/public/images/backgrounds/overlay_1.svg
  client/public/images/portrait/portrait_1.jpg
  client/public/images/portrait/portrait_2.jpg
  client/public/images/portrait/portrait_3.jpg
  client/public/images/portrait/portrait_4.jpg
  client/src/App.scss
  client/src/config/routes.ts
  client/src/layouts/components/Header.tsx
  client/src/pages/AboutUs/AboutUs.tsx
  client/src/pages/AboutUs/CommentCard.tsx
  client/src/pages/AboutUs/MemberCard.tsx
  client/src/pages/AboutUs/index.ts
  client/src/routes/router/mainRouter.tsx
  client/src/types/CommentType.ts
  client/src/types/MemberType.ts
Labels: Need to be reviewed

#14 Update Verify Email
  .vscode/launch.json
  server/src/app/controllers/auth.js
  server/src/app/middlewares/auth.js
  server/src/app/models/User.js
  server/src/routes/auth.js
  server/src/utils/email.js
  server/src/utils/otp.js
Labels: Bug

#18 ContactUs
  client/public/images/contact/hero.jpg
  client/src/App.scss
  client/src/config/routes.ts
  client/src/layouts/components/Header.tsx
  client/src/pages/ContactUs/ContactUs.tsx
  client/src/pages/ContactUs/index.ts
  client/src/routes/router/mainRouter.tsx
Labels: Need to improve

#20 Me/filter and search products
  server/src/app/controllers/product.js
  server/src/utils/APIFeatures.js
Labels: Need to be reviewed
